#!/bin/bash

#   _ 
#  | |                                         
#  | |__  ___ _ ____      ___ __ ___  _ __ ___ 
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#  | |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#            | |                               
#            |_|                               


## Áreas de Trabalho -------------------------------------------------#

bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9'

## Configurações gerais ----------------------------------------------#

bspc config border_width 3
bspc config window_gap 8
bspc config split_ratio 0.50
bspc config top_padding 25

bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config single_monocle false
bspc config paddingless_monocle true
bspc config focus_follows_pointer true

## Color Schemes -----------------------------------------------------#

. $HOME/.config/bspwm/everforest

bspc config focused_border_color $focused 
bspc config normal_border_color  $normal
bspc config active_border_color  $active
bspc config presel_feedback_color $presel

## Window rules ------------------------------------------------------#

## remove all rules first
bspc rule -r *:*

# WP 1 (web)
bspc rule -a Firefox-esr desktop=^1
# WP 2 (web)
bspc rule -a firefox desktop=^2 follow=on focus=on
# WP 3 (terminal padrão)
bspc rule -a Xfce4-terminal=^3
# WP 4 (gerenciador de arquivos)
bspc rule -a Thunar desktop=^4 follow=on focus=on
# WP 5 (música/vídeo)
bspc rule -a cmus desktop=^5
bspc rule -a Musescore desktop=^5
bspc rule -a smplayer desktop=^5
bspc rule -a mpv desktop=^5
# WP 6 (outros terminais)
bspc rule -a Alacritty desktop=^3
bspc rule -a Lxterminal desktop=^3
# WP 7 (texto, edição e visualização de arquivos)
bspc rule -a Atril desktop=^7
bspc rule -a Evince desktop=^7
bspc rule -a Gimp-2.10 desktop=^7 follow=on focus=on
bspc rule -a libreoffice-startcenter desktop=^7 focus=on
bspc rule -a libreoffice-writer desktop=^7
bspc rule -a Mousepad desktop=^7 follow=on focus=on
# WP 8 (jogos)
bspc rule -a Mednaffe desktop=^8 follow=on focus=on 
bspc rule -a mGBA desktop=^8
bspc rule -a ResidualVM desktop=^8
bspc rule -a scummVM desktop=^8 folow=on focus=on
# WP 9 (outros)
bspc rule -a KeePassXC desktop=^9 follow=on focus=on
bspc rule -a qBittorrent desktop=^9
bspc rule -a SiriKali desktop=^9 follow=on focus=on
bspc rule -a Virt-manager desktop=^9 follow=on focus=on

## Janelas flutuantes
bspc rule -a Galculator state=floating
bspc rule -a mGBA statue=floating
bspc rule -a libreoffice-startcenter statue=floating

## Compositor ------------------------------------------------------#
picom &

## "Gerenciador de atalhos" (hotkey daemon) ------------------------#
sxhkd &

## Fix cursor ------------------------------------------------------#
xsetroot -cursor_name left_ptr

## Wallpaper -------------------------------------------------------#
feh --bg-fill $wall

## Painel (polybar) ------------------------------------------------#
~/.config/polybar/polybar-bspwm/launch.sh

## Gerenciador de Notificações -------------------------------------#
/usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd &

## Resolução da Tela -----------------------------------------------#
xrandr -s 1360x768

## Monitor de Recursos do Sistema ----------------------------------# 
psensor &

# Network-Manager na systray ---------------------------------------#
#nm-applet &

# Gnome polkit -----------------------------------------------------#
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# Numlock no boot --------------------------------------------------#
numlockx &
